import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// {@template jetleaf_toolchain_versions}
/// Resolves the framework and tooling versions recorded in project state.
///
/// Version values are build metadata, not CLI configuration. They must come
/// from the same dependency resolution that produced the project, otherwise a
/// descriptor can claim that it was generated by a different framework than
/// the one actually selected by `pub get`.
///
/// Resolution uses the following order:
///
/// 1. `pubspec.lock`, which is the authoritative resolved dependency graph.
/// 2. The nearest valid `.dart_tool/package_config.json` and the package
///    pubspecs it resolves, which also supports workspace package execution.
/// 3. `.dart_tool/package_graph.json` when package configuration is not
///    available yet.
/// 4. `Unknown`, when the project has not yet produced package metadata.
///
/// No package version is hard-coded in this resolver. This is important for
/// workspace development, path dependencies, released applications, and
/// future CLI versions.
/// {@endtemplate}
final class JetleafToolchainVersions {
  /// {@macro jetleaf_toolchain_versions}
  const JetleafToolchainVersions._();

  /// Package names whose resolved versions are written to project state.
  static const List<String> _trackedPackages = [
    'jetleaf',
    'jetleaf_cli',
    'jetleaf_build',
    'jetleaf_core',
  ];

  /// Resolves framework/tooling versions for [projectRoot].
  ///
  /// **Returns:** a stable map suitable for the `toolchain` section of the
  /// root `Jetleaf` document. Dart's full version string is retained under
  /// `dartVersion` because it is useful when diagnosing SDK-sensitive caches.
  static Future<Map<String, Object?>> resolve(Directory projectRoot) async {
    final locked = await _readLockVersions(projectRoot);
    final packageVersions = await _readPackageConfigVersions(projectRoot);
    final graphVersions = await _readPackageGraphVersions(projectRoot);

    String versionFor(String packageName) =>
        locked[packageName] ??
        packageVersions[packageName] ??
        graphVersions[packageName] ??
        'Unknown';

    return {
      'jetleafVersion': versionFor('jetleaf'),
      'cliVersion': versionFor('jetleaf_cli'),
      'buildVersion': versionFor('jetleaf_build'),
      'coreVersion': versionFor('jetleaf_core'),
      'dartVersion': Platform.version,
    };
  }

  /// Reads resolved package versions from the project's lock file.
  static Future<Map<String, String>> _readLockVersions(
    Directory projectRoot,
  ) async {
    final file = _findUpward(projectRoot, 'pubspec.lock');
    if (file == null) return const {};

    try {
      final document = loadYaml(await file.readAsString());
      final packages = document is YamlMap ? document['packages'] : null;
      if (packages is! YamlMap) return const {};

      final versions = <String, String>{};
      for (final packageName in _trackedPackages) {
        final package = packages[packageName];
        final version = package is YamlMap ? package['version'] : null;
        if (version is String && version.isNotEmpty) {
          versions[packageName] = version;
        }
      }
      return versions;
    } catch (_) {
      // A malformed or partially written lock file must not prevent project
      // detection. The package-config fallback still provides useful data.
      return const {};
    }
  }

  /// Reads package-local pubspec versions through package configuration.
  static Future<Map<String, String>> _readPackageConfigVersions(
    Directory projectRoot,
  ) async {
    final file = _findUpward(
      projectRoot,
      p.join('.dart_tool', 'package_config.json'),
    );
    if (file == null) return const {};

    try {
      final document = jsonDecode(await file.readAsString());
      final packages = document is Map<String, dynamic>
          ? document['packages']
          : null;
      if (packages is! List) return const {};

      final versions = <String, String>{};
      for (final value in packages) {
        if (value is! Map<String, dynamic>) continue;
        final name = value['name'];
        if (name is! String || !_trackedPackages.contains(name)) continue;
        final rootUri = value['rootUri'];
        if (rootUri is! String) continue;

        final root = _resolveRootUri(rootUri, file.parent);
        final pubspec = File(p.join(root.path, 'pubspec.yaml'));
        if (!pubspec.existsSync()) continue;
        final version = await _readPubspecVersion(pubspec);
        if (version != null) versions[name] = version;
      }
      return versions;
    } catch (_) {
      return const {};
    }
  }

  /// Reads package versions from the local package graph when no package
  /// configuration is available yet.
  static Future<Map<String, String>> _readPackageGraphVersions(
    Directory projectRoot,
  ) async {
    final file = _findUpward(
      projectRoot,
      p.join('.dart_tool', 'package_graph.json'),
    );
    if (file == null) return const {};

    try {
      final document = jsonDecode(await file.readAsString());
      final packages = document is Map<String, dynamic>
          ? document['packages']
          : null;
      if (packages is! List) return const {};

      final versions = <String, String>{};
      for (final value in packages) {
        if (value is! Map<String, dynamic>) continue;
        final name = value['name'];
        final version = value['version'];
        if (name is String &&
            version is String &&
            _trackedPackages.contains(name) &&
            version.isNotEmpty) {
          versions[name] = version;
        }
      }
      return versions;
    } catch (_) {
      return const {};
    }
  }

  /// Finds the nearest metadata file from [root] or one of its parents.
  ///
  /// This supports ordinary projects with local `.dart_tool` state and
  /// workspace projects whose executable is resolved from the workspace
  /// package configuration.
  static File? _findUpward(Directory root, String relativePath) {
    var directory = Directory(p.normalize(root.absolute.path));
    while (true) {
      final candidate = File(p.join(directory.path, relativePath));
      if (candidate.existsSync()) return candidate;

      final parent = Directory(p.normalize(p.join(directory.path, '..')));
      if (parent.path == directory.path) return null;
      directory = parent;
    }
  }

  /// Resolves a package-config root URI relative to its JSON file.
  static Directory _resolveRootUri(String value, Directory configDirectory) {
    final uri = Uri.parse(value);
    if (uri.scheme == 'file') return Directory.fromUri(uri);
    return Directory(p.normalize(p.join(configDirectory.path, value)));
  }

  /// Reads only the package version field from a package pubspec.
  static Future<String?> _readPubspecVersion(File file) async {
    try {
      final document = loadYaml(await file.readAsString());
      final version = document is YamlMap ? document['version'] : null;
      return version is String && version.isNotEmpty ? version : null;
    } catch (_) {
      return null;
    }
  }
}
